### PR TITLE
reconfigurated to asg-1

### PR DESCRIPTION
**Pull request by tsangkafu**
reconfigured react-app to "asg-1"

### CODE REVIEW

**Comment by tsangkafu** [comment]
please review this code and merge to dev first, before that I cant branch out from dev

**Comment by chaoxdrag920** [comment]
can you add me as a reviewer, i saw some typos

**Comment by chaoxdrag920** [comment]
spelling error line 10 in App.js: favoriteVisiable -> favoriteVisible (spelling error)

**Comment by chaoxdrag920** [comment]
> spelling error line 10 in App.js: favoriteVisiable -> favoriteVisible (spelling error)

>spelling error line 12 in App.js: setfavoriteVisiable -> setFavoriteVisible (spelling error +camel case it)

>change the corresponding reoccurences

**Comment by chaoxdrag920** [comment]
lgtm `434608d6cbb01e155859b9512a7e8ee41bdb2b4`. You can merge once those spelling mistakes are changed. I will work on search and filters tomorrow

**Pull request merged**
